site_name: My Docs
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections

site_url: "https://jeffersglass.github.io/miketest"

extra:
  version:
    provider: mike
    default: 'latest'

plugins:
    - mkdocs-pyscript:
        pyscript_version: "snapshots/2023.11.1.RC3"

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
      alternate_style: true
- admonition
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
